name: nats_dart
description: NATS client for Dart.
version: 2.0.0
homepage: https://github.com/tejainece/dart_nats
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0-dev.65 <3.0.0'

# dependencies:

dev_dependencies:
  test: ^1.0.0
